//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cold_Drinks_CURD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblColdDrink
    {
        public int intColdDrinksId { get; set; }
        public string strColdDrinksName { get; set; }
        public Nullable<decimal> numQuantity { get; set; }
        public Nullable<decimal> numUnitPrice { get; set; }
    }
}
